plugins {
    id 'java'
}

group = 'com.clubnu'
version = '0.0.1-SNAPSHOT'

bootJar {enabled = false}
jar {enabled = true}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':clubnu-common')
    // feign
    implementation("org.springframework.cloud:spring-cloud-starter-openfeign:4.1.0")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
}

test {
    useJUnitPlatform()
}